version: '3'

services:
  locust-master:
    image: locustio/locust:2.32.6
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://localhost
    networks:
      - locust-net

  locust-worker:
    image: locustio/locust:2.32.6
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    networks:
      - locust-net
    depends_on:
      - locust-master
    deploy:
      replicas: 4

networks:
  locust-net:
    driver: bridge

